version: '3.8'

services:
  db:
    container_name: postgres-task-3
    image: postgres
    restart: always
    env_file:
      - .env
    environment:
      - POSTGRES_USER=${TYPEORM_USERNAME}
      - POSTGRES_PASSWORD=${TYPEORM_PASSWORD}
      - POSTGRES_DB=${TYPEORM_DATABASE}
    volumes: 
    - ./pgdata:/var/lib/postgres/data
    ports:
      - ${TYPEORM_PORT}:${TYPEORM_PORT}
